# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [4]:
z=np.zeros(10)
z.astype(np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

3. Create a vector with values ranging from 10 to 49

In [5]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [6]:
z=np.arange(10,49)
np.shape(z)

(39,)

5. Print the type of the previous array in question 3

In [8]:
z.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [9]:
np.__version__

'1.18.5'

In [10]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/f/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/f/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/f/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/f/

7. Print the dimension of the array in question 3


In [11]:
z.ndim

1

8. Create a boolean array with all the True values

In [13]:
z=np.arange(10)
z.astype(np.bool)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [14]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

10. Create a three dimensional array



In [15]:
np.arange(64).reshape(4,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [17]:
z=np.arange(10)
z[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [24]:
z=np.zeros(10)
z[5]=1
z.astype(np.int32)

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [25]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [26]:
arr=np.array([1,2,3,4,5])
arr.astype(np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [27]:
arr1=np.array([[1.,2.,3.] , [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [4]:
arr1=np.array([[1.,2.,3.] , [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr3=arr1==arr2
arr3.all()

False

17. Extract all odd numbers from arr with values(0-9)

In [10]:
arr1=np.arange(10)
arr1[arr1%2==1]


array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [12]:
arr1=np.arange(10)
arr1[arr1%2==1]=-1
arr1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [15]:
arr=np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [32]:
arr=np.ones((4,5) , dtype="int32")
arr[1:-1,1:-1]=0
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [34]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [35]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0:1]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [42]:
arr=np.arange(10).reshape(2,5)
arr[0:1,0:5]

array([[0, 1, 2, 3, 4]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [43]:
arr=np.arange(10).reshape(2,5)
arr[1:,0:5]

array([[5, 6, 7, 8, 9]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [44]:
arr=np.arange(10).reshape(2,5)
arr[0:2,3:4]

array([[3],
       [8]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [50]:
arr=np.random.rand(10,10)
arr.max(),arr.min()

(0.9916476461618671, 0.002156731775832532)

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [53]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)            #intersect1d basically use for create a common between arrays

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [54]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [55]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names!='Will']

array([[-1.48475567,  0.31043505, -0.81045816, -0.49567405],
       [ 0.99990369, -0.37127177, -0.4590353 ,  0.30339512],
       [-0.46684586, -1.00433405, -0.26241962,  0.50036821],
       [-1.2817444 , -0.57769258,  1.44399597,  1.14547264],
       [-0.00854885, -0.28167516,  1.27955592,  0.09151753]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [56]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
mask=(names!='Will') & (names!='Joe')
data[mask]

array([[-0.13158722,  1.15150056,  1.92427798, -0.38591038],
       [ 1.94309717, -0.22338993, -0.72623411, -0.41681758]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [3]:
arr=np.arange(15).reshape(5,3)
arr.astype(np.float32)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]], dtype=float32)

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [4]:
arr=np.arange(16).reshape(2,2,4)
arr.astype(np.float32)

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]], dtype=float32)

33. Swap axes of the array you created in Question 32

In [8]:
arr=np.arange(16).reshape(2,2,4)
arr.astype(np.float32)
np.swapaxes(arr ,0,2)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [40]:
names=np.arange(10)/2
names[names<0.5]=0
names

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [10]:
a=np.random.rand(4,3)
b=np.random.rand(3,4)
a.max() , b.max()

(0.9928670094453882, 0.9574075631298896)

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [11]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [12]:
 a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [18]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
arr=np.delete(sampleArray , 1 , axis=1)
newColumn = np.array([[10,10,10]])
np.insert(arr, 1, newColumn ,axis=1 )

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [19]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [33]:
z=np.random.random((5,4))
np.cumsum(z)

array([0.38214381, 0.41068926, 1.27083309, 2.16687379, 2.87453458,
       3.24853907, 3.50722817, 4.34562294, 4.55467354, 4.72544028,
       5.57466983, 6.07389234, 6.44857209, 7.18687642, 7.3929934 ,
       7.71954221, 7.84454083, 7.96972547, 8.83488675, 9.21955083])